export type SKILL_TYPE =
  | 'Javascript'
  | 'Typescript'
  | 'Python'
  | 'Java'
  | 'PHP'
  | 'SQL'
  | 'C'
  | 'C#'
  | 'C++'
  | 'Go'
  | 'Ruby'
  | 'Node JS'
  | 'Express JS'
  | 'Nest JS'
  | 'React JS'
  | 'Flask'
  | 'Fast API'
  | 'Spring'
  | 'Spring Boot'
  | 'Next JS'
  | 'Vue JS'
  | 'Angular JS'
  | 'Nuxt JS'
  | 'RESTful API'
  | 'GraphQL'
  | 'Redux'
  | 'Fastify'
  | 'Django'
  | 'Object C'
  | 'Kotlin'
  | 'Unity'
  | 'Unreal Engine'
  | 'HTML'
  | 'CSS'
  | 'Style Component'
  | 'React Native'
  | 'Flutter'
  | 'AWS'
  | 'GCP'
  | 'Azure'
  | 'Heroku'
  | 'Firebase'
  | 'MySQL'
  | 'PostgreSQL'
  | 'MariaDB'
  | 'MongoDB'
  | 'Redis'
  | 'Story Book'
  | 'Git'
  | 'Github'
  | 'GitLab'
  | 'Bit Bucket'
  | 'Jenkins'
  | 'Github Action'
  | 'ORACLE'
  | 'Figma'
  | 'Zeplin'
  | 'Adobe Photoshop'
  | 'Adobe Illustrator'
  | 'Adobe XD'
  | 'Notion'
  | 'Spread Sheet'
  | 'Excel'
  | 'Power Point'
  | 'Power Mockup'
  | 'PDF'
  | 'Story Board'
  | 'Prototyping'
  | 'Sketch'
  | 'InDesign'
  | 'Oven'
  | 'Axure'
  | 'Experience Design CC'
  | 'InVision';
